(function () {
  const features = [
    { key: "sunday_roast", label: "Sunday roast", shortLabel: "Roast", hard: true },
    { key: "dog_friendly", label: "Dog friendly", shortLabel: "Dogs", hard: true },
    { key: "beer_garden", label: "Beer garden", shortLabel: "Garden", hard: true },
    { key: "pub_quiz", label: "Pub quiz", shortLabel: "Quiz", hard: false },
    { key: "live_music", label: "Live music", shortLabel: "Music", hard: false },
    { key: "craft_beer", label: "Craft beer", shortLabel: "Craft", hard: false },
    { key: "dart_board", label: "Dart board", shortLabel: "Darts", hard: false },
    { key: "pool_table", label: "Pool table", shortLabel: "Pool", hard: false },
    { key: "showing_football", label: "Showing football", shortLabel: "Football", hard: true }
  ];

  const weekdayStandard = {
    0: [[720, 1380]],
    1: [[720, 1380]],
    2: [[720, 1380]],
    3: [[720, 1380]],
    4: [[720, 1380]],
    5: [[720, 1500]],
    6: [[720, 1500]]
  };

  const foodLed = {
    0: [[720, 1320]],
    1: [[720, 1380]],
    2: [[720, 1380]],
    3: [[720, 1380]],
    4: [[720, 1380]],
    5: [[720, 1440]],
    6: [[720, 1440]]
  };

  const centralLate = {
    0: [[720, 1380]],
    1: [[720, 1380]],
    2: [[720, 1380]],
    3: [[720, 1440]],
    4: [[720, 1440]],
    5: [[720, 1500]],
    6: [[720, 1500]]
  };

  const quietLocal = {
    0: [[720, 1320]],
    1: [[960, 1380]],
    2: [[960, 1380]],
    3: [[960, 1380]],
    4: [[960, 1380]],
    5: [[720, 1440]],
    6: [[720, 1440]]
  };

  const makeFeatures = (overrides) =>
    features.reduce((acc, feature) => {
      acc[feature.key] = Boolean(overrides[feature.key]);
      return acc;
    }, {});

  const locationPresets = [
    {
      name: "Walthamstow",
      area: "Walthamstow",
      lat: 51.5829,
      lng: -0.0199,
      transitScore: 8,
      aliases: ["walthamstow", "walthamstow central", "e17"]
    },
    {
      name: "Clapham",
      area: "Clapham",
      lat: 51.4622,
      lng: -0.1388,
      transitScore: 8,
      aliases: ["clapham", "clapham common", "clapham north", "sw4"]
    },
    {
      name: "Camden",
      area: "Camden",
      lat: 51.539,
      lng: -0.1426,
      transitScore: 9,
      aliases: ["camden", "camden town", "nw1"]
    },
    {
      name: "Hackney",
      area: "Hackney",
      lat: 51.547,
      lng: -0.0553,
      transitScore: 7,
      aliases: ["hackney", "hackney central", "e8"]
    },
    {
      name: "Angel",
      area: "Islington",
      lat: 51.5326,
      lng: -0.1059,
      transitScore: 9,
      aliases: ["angel", "angel station", "islington", "n1"]
    },
    {
      name: "Finsbury Park",
      area: "Finsbury Park",
      lat: 51.5647,
      lng: -0.106,
      transitScore: 10,
      aliases: ["finsbury park", "n4"]
    },
    {
      name: "King's Cross",
      area: "King's Cross",
      lat: 51.532,
      lng: -0.1233,
      transitScore: 10,
      aliases: ["kings cross", "king's cross", "st pancras", "wc1"]
    },
    {
      name: "London Bridge",
      area: "London Bridge",
      lat: 51.5055,
      lng: -0.0865,
      transitScore: 10,
      aliases: ["london bridge", "se1"]
    },
    {
      name: "Soho",
      area: "Soho",
      lat: 51.5136,
      lng: -0.1365,
      transitScore: 9,
      aliases: ["soho", "piccadilly circus", "w1"]
    },
    {
      name: "Shoreditch",
      area: "Shoreditch",
      lat: 51.526,
      lng: -0.078,
      transitScore: 8,
      aliases: ["shoreditch", "shoreditch high street", "hoxton", "e1"]
    },
    {
      name: "Brixton",
      area: "Brixton",
      lat: 51.4626,
      lng: -0.1149,
      transitScore: 9,
      aliases: ["brixton", "sw2", "sw9"]
    },
    {
      name: "Stratford",
      area: "Stratford",
      lat: 51.5416,
      lng: -0.0038,
      transitScore: 10,
      aliases: ["stratford", "stratford international", "e15"]
    },
    {
      name: "Dalston",
      area: "Dalston",
      lat: 51.545,
      lng: -0.074,
      transitScore: 8,
      aliases: ["dalston", "dalston junction", "e8 dalston"]
    },
    {
      name: "Stoke Newington",
      area: "Stoke Newington",
      lat: 51.5615,
      lng: -0.0731,
      transitScore: 6,
      aliases: ["stoke newington", "stokey", "n16"]
    },
    {
      name: "Hammersmith",
      area: "Hammersmith",
      lat: 51.4927,
      lng: -0.2246,
      transitScore: 9,
      aliases: ["hammersmith", "w6"]
    },
    {
      name: "Battersea",
      area: "Battersea",
      lat: 51.4817,
      lng: -0.159,
      transitScore: 7,
      aliases: ["battersea", "battersea park", "sw11"]
    },
    {
      name: "Vauxhall",
      area: "Vauxhall",
      lat: 51.4861,
      lng: -0.1233,
      transitScore: 9,
      aliases: ["vauxhall", "se11"]
    },
    {
      name: "Waterloo",
      area: "Waterloo",
      lat: 51.5033,
      lng: -0.1147,
      transitScore: 10,
      aliases: ["waterloo", "south bank"]
    },
    {
      name: "Victoria",
      area: "Victoria",
      lat: 51.4965,
      lng: -0.1447,
      transitScore: 10,
      aliases: ["victoria", "westminster", "sw1"]
    },
    {
      name: "Greenwich",
      area: "Greenwich",
      lat: 51.4781,
      lng: -0.0081,
      transitScore: 7,
      aliases: ["greenwich", "se10"]
    },
    {
      name: "Deptford",
      area: "Deptford",
      lat: 51.4788,
      lng: -0.0266,
      transitScore: 7,
      aliases: ["deptford", "se8"]
    },
    {
      name: "Peckham",
      area: "Peckham",
      lat: 51.4709,
      lng: -0.067,
      transitScore: 7,
      aliases: ["peckham", "peckham rye", "se15"]
    },
    {
      name: "Lewisham",
      area: "Lewisham",
      lat: 51.4657,
      lng: -0.014,
      transitScore: 8,
      aliases: ["lewisham", "se13"]
    },
    {
      name: "Tooting",
      area: "Tooting",
      lat: 51.4276,
      lng: -0.168,
      transitScore: 7,
      aliases: ["tooting", "tooting broadway", "sw17"]
    },
    {
      name: "Balham",
      area: "Balham",
      lat: 51.4433,
      lng: -0.1527,
      transitScore: 8,
      aliases: ["balham", "sw12"]
    },
    {
      name: "Putney",
      area: "Putney",
      lat: 51.4613,
      lng: -0.216,
      transitScore: 7,
      aliases: ["putney", "sw15"]
    },
    {
      name: "Ealing Broadway",
      area: "Ealing",
      lat: 51.5149,
      lng: -0.3015,
      transitScore: 9,
      aliases: ["ealing", "ealing broadway", "w5"]
    },
    {
      name: "Paddington",
      area: "Paddington",
      lat: 51.5154,
      lng: -0.1755,
      transitScore: 10,
      aliases: ["paddington", "w2"]
    },
    {
      name: "Canary Wharf",
      area: "Canary Wharf",
      lat: 51.5054,
      lng: -0.0235,
      transitScore: 9,
      aliases: ["canary wharf", "e14"]
    },
    {
      name: "Wimbledon",
      area: "Wimbledon",
      lat: 51.4214,
      lng: -0.2064,
      transitScore: 8,
      aliases: ["wimbledon", "sw19"]
    },
    {
      name: "Richmond",
      area: "Richmond",
      lat: 51.4613,
      lng: -0.3037,
      transitScore: 7,
      aliases: ["richmond", "tw9"]
    },
    {
      name: "Tottenham Hale",
      area: "Tottenham",
      lat: 51.5882,
      lng: -0.0594,
      transitScore: 9,
      aliases: ["tottenham hale", "tottenham", "n17"]
    },
    {
      name: "Seven Sisters",
      area: "Seven Sisters",
      lat: 51.5827,
      lng: -0.0753,
      transitScore: 8,
      aliases: ["seven sisters", "n15"]
    }
  ];

  const pubs = [
    {
      id: "pub_001",
      googlePlaceId: "seed_faltering_fullback",
      name: "The Faltering Fullback",
      area: "Finsbury Park",
      address: "19 Perth Road, London N4 3HB",
      lat: 51.5681,
      lng: -0.1077,
      transitScore: 9,
      googleRating: 4.5,
      reviewCount: 2890,
      priceLevel: 2,
      estimatedPintPrice: 6.6,
      openingHours: centralLate,
      website: "https://www.falteringfullback.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Faltering+Fullback+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "",
      sportsInfo: "Screens major football and rugby fixtures.",
      sundayRoastInfo: "Sunday roasts are popular and best booked ahead.",
      reviewSummary: {
        sentiment: "Mostly positive",
        themes: ["layered beer garden", "lively sports crowd", "friendly regulars"],
        concerns: ["very busy after work and on match days"]
      },
      busyProfile: { base: "busy", centrality: 6, quizDay: null, sportsPull: 2, roastPull: 1 },
      adminNotes: "Signature pub garden, strong for larger groups if they arrive early."
    },
    {
      id: "pub_002",
      googlePlaceId: "seed_alma_islington",
      name: "The Alma",
      area: "Islington",
      address: "59 Newington Green Road, London N1 4QU",
      lat: 51.5512,
      lng: -0.0868,
      transitScore: 7,
      googleRating: 4.4,
      reviewCount: 690,
      priceLevel: 2,
      estimatedPintPrice: 6.4,
      openingHours: foodLed,
      website: "https://thealmapub.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Alma+Islington+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "Tuesday",
      sportsInfo: "Quiet on sport compared with nearby match pubs.",
      sundayRoastInfo: "Known locally for Sunday lunch.",
      reviewSummary: {
        sentiment: "Mostly positive",
        themes: ["food", "warm service", "neighbourhood feel"],
        concerns: ["limited outside space"]
      },
      busyProfile: { base: "moderate", centrality: 4, quizDay: 2, sportsPull: 0, roastPull: 2 },
      adminNotes: "Good food-first choice near Newington Green."
    },
    {
      id: "pub_003",
      googlePlaceId: "seed_crown_stokey",
      name: "The Crown",
      area: "Stoke Newington",
      address: "223 Grove Road, London N16 9ES",
      lat: 51.5629,
      lng: -0.0744,
      transitScore: 6,
      googleRating: 4.2,
      reviewCount: 1170,
      priceLevel: 2,
      estimatedPintPrice: 6.3,
      openingHours: centralLate,
      website: "https://www.thecrownn16.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Crown+Stoke+Newington+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: true,
        showing_football: true
      }),
      quizNight: "Wednesday",
      sportsInfo: "Shows football in the main bar.",
      sundayRoastInfo: "Roasts available Sundays.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["busy garden", "quiz nights", "group-friendly"],
        concerns: ["journeys can be slower without the Tube"]
      },
      busyProfile: { base: "busy", centrality: 4, quizDay: 3, sportsPull: 2, roastPull: 2 },
      adminNotes: "Strong feature match but not as transport-connected as Finsbury Park."
    },
    {
      id: "pub_004",
      googlePlaceId: "seed_southampton_arms",
      name: "The Southampton Arms",
      area: "Gospel Oak",
      address: "139 Highgate Road, London NW5 1LE",
      lat: 51.5522,
      lng: -0.1494,
      transitScore: 7,
      googleRating: 4.6,
      reviewCount: 1910,
      priceLevel: 2,
      estimatedPintPrice: 6.1,
      openingHours: quietLocal,
      website: "https://www.thesouthamptonarms.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Southampton+Arms+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "No regular sport focus.",
      sundayRoastInfo: "Food is simple rather than roast-led.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["ale and cider", "independent feel", "simple snacks"],
        concerns: ["small room fills quickly"]
      },
      busyProfile: { base: "moderate", centrality: 4, quizDay: null, sportsPull: 0, roastPull: 0 },
      adminNotes: "Excellent beer quality; better for smaller groups."
    },
    {
      id: "pub_005",
      googlePlaceId: "seed_harp_covent_garden",
      name: "The Harp",
      area: "Covent Garden",
      address: "47 Chandos Place, London WC2N 4HS",
      lat: 51.5092,
      lng: -0.1256,
      transitScore: 10,
      googleRating: 4.7,
      reviewCount: 3450,
      priceLevel: 2,
      estimatedPintPrice: 6.8,
      openingHours: centralLate,
      website: "https://www.harpcoventgarden.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Harp+Covent+Garden+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Traditional beer pub, not sport-led.",
      sundayRoastInfo: "Not a roast-first pub.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["cask ale", "central location", "classic London pub"],
        concerns: ["standing room at peak times"]
      },
      busyProfile: { base: "busy", centrality: 10, quizDay: null, sportsPull: 0, roastPull: 0 },
      adminNotes: "High-quality central beer choice; often packed."
    },
    {
      id: "pub_006",
      googlePlaceId: "seed_wenlock_arms",
      name: "The Wenlock Arms",
      area: "Hoxton",
      address: "26 Wenlock Road, London N1 7TA",
      lat: 51.5297,
      lng: -0.0933,
      transitScore: 7,
      googleRating: 4.6,
      reviewCount: 1510,
      priceLevel: 2,
      estimatedPintPrice: 6.2,
      openingHours: weekdayStandard,
      website: "https://www.wenlockarms.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Wenlock+Arms+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: true,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "No regular sport focus.",
      sundayRoastInfo: "Beer-led rather than food-led.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["real ale", "old-school room", "knowledgeable bar staff"],
        concerns: ["limited food"]
      },
      busyProfile: { base: "moderate", centrality: 6, quizDay: null, sportsPull: 0, roastPull: 0 },
      adminNotes: "Reliable craft and cask pick near Old Street."
    },
    {
      id: "pub_007",
      googlePlaceId: "seed_dove_hammersmith",
      name: "The Dove",
      area: "Hammersmith",
      address: "19 Upper Mall, London W6 9TA",
      lat: 51.4909,
      lng: -0.2353,
      transitScore: 7,
      googleRating: 4.4,
      reviewCount: 3280,
      priceLevel: 3,
      estimatedPintPrice: 7.2,
      openingHours: foodLed,
      website: "https://www.dovehammersmith.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Dove+Hammersmith+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Riverside food pub rather than sport pub.",
      sundayRoastInfo: "Sunday roasts with riverside demand.",
      reviewSummary: {
        sentiment: "Mostly positive",
        themes: ["riverside setting", "history", "roasts"],
        concerns: ["premium prices", "tourist demand"]
      },
      busyProfile: { base: "busy", centrality: 5, quizDay: null, sportsPull: 0, roastPull: 2 },
      adminNotes: "Great west London option, less fair for east-heavy groups."
    },
    {
      id: "pub_008",
      googlePlaceId: "seed_bull_last",
      name: "The Bull and Last",
      area: "Highgate",
      address: "168 Highgate Road, London NW5 1QS",
      lat: 51.5572,
      lng: -0.1498,
      transitScore: 6,
      googleRating: 4.5,
      reviewCount: 1170,
      priceLevel: 3,
      estimatedPintPrice: 7.0,
      openingHours: foodLed,
      website: "https://www.thebullandlast.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Bull+and+Last+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Food-led pub, not sport-led.",
      sundayRoastInfo: "Destination Sunday roast.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["food", "Sunday lunch", "polished service"],
        concerns: ["price", "booking needed"]
      },
      busyProfile: { base: "busy", centrality: 4, quizDay: null, sportsPull: 0, roastPull: 3 },
      adminNotes: "Strong food quality; not ideal for cheap-pint searches."
    },
    {
      id: "pub_009",
      googlePlaceId: "seed_eagle_farringdon",
      name: "The Eagle",
      area: "Farringdon",
      address: "159 Farringdon Road, London EC1R 3AL",
      lat: 51.5242,
      lng: -0.1099,
      transitScore: 9,
      googleRating: 4.4,
      reviewCount: 1590,
      priceLevel: 2,
      estimatedPintPrice: 6.7,
      openingHours: centralLate,
      website: "https://www.theeaglefarringdon.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Eagle+Farringdon+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Gastropub rather than sport pub.",
      sundayRoastInfo: "Food changes often; Sunday lunch available.",
      reviewSummary: {
        sentiment: "Mostly positive",
        themes: ["food", "central convenience", "classic gastropub"],
        concerns: ["can feel cramped"]
      },
      busyProfile: { base: "busy", centrality: 8, quizDay: null, sportsPull: 0, roastPull: 2 },
      adminNotes: "Very convenient central option for mixed north/south groups."
    },
    {
      id: "pub_010",
      googlePlaceId: "seed_three_johns",
      name: "The Three Johns",
      area: "Islington",
      address: "73 White Lion Street, London N1 9PF",
      lat: 51.5323,
      lng: -0.1095,
      transitScore: 9,
      googleRating: 4.3,
      reviewCount: 1250,
      priceLevel: 2,
      estimatedPintPrice: 6.7,
      openingHours: centralLate,
      website: "https://thethreejohns.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Three+Johns+Islington+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Monday",
      sportsInfo: "Screens major fixtures.",
      sundayRoastInfo: "Sunday roasts and pizzas.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["Angel location", "beer choice", "pizza"],
        concerns: ["gets noisy"]
      },
      busyProfile: { base: "busy", centrality: 8, quizDay: 1, sportsPull: 2, roastPull: 1 },
      adminNotes: "A solid Angel fallback when the midpoint points central-north."
    },
    {
      id: "pub_011",
      googlePlaceId: "seed_peoples_park_tavern",
      name: "People's Park Tavern",
      area: "Victoria Park",
      address: "360 Victoria Park Road, London E9 7BT",
      lat: 51.5364,
      lng: -0.0419,
      transitScore: 6,
      googleRating: 4.2,
      reviewCount: 2390,
      priceLevel: 2,
      estimatedPintPrice: 6.5,
      openingHours: centralLate,
      website: "https://www.peoplesparktavern.pub/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=People's+Park+Tavern+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Tuesday",
      sportsInfo: "Shows selected sport.",
      sundayRoastInfo: "Popular Sunday roast and garden combination.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["huge garden", "park setting", "group tables"],
        concerns: ["weekend queues"]
      },
      busyProfile: { base: "busy", centrality: 5, quizDay: 2, sportsPull: 1, roastPull: 2 },
      adminNotes: "Excellent garden pub for east and north-east groups."
    },
    {
      id: "pub_012",
      googlePlaceId: "seed_commercial_tavern",
      name: "The Commercial Tavern",
      area: "Shoreditch",
      address: "142 Commercial Street, London E1 6NU",
      lat: 51.5215,
      lng: -0.073,
      transitScore: 8,
      googleRating: 4.4,
      reviewCount: 1180,
      priceLevel: 2,
      estimatedPintPrice: 6.6,
      openingHours: centralLate,
      website: "https://www.commercialtavern.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Commercial+Tavern+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: false,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Not a sports pub.",
      sundayRoastInfo: "Limited food focus.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["quirky rooms", "late nights", "Shoreditch energy"],
        concerns: ["busy weekend evenings"]
      },
      busyProfile: { base: "busy", centrality: 8, quizDay: null, sportsPull: 0, roastPull: 0 },
      adminNotes: "Good social-energy pick, weak for quiet searches."
    },
    {
      id: "pub_013",
      googlePlaceId: "seed_queens_head_kx",
      name: "The Queen's Head",
      area: "King's Cross",
      address: "66 Acton Street, London WC1X 9NB",
      lat: 51.5273,
      lng: -0.1168,
      transitScore: 10,
      googleRating: 4.5,
      reviewCount: 1380,
      priceLevel: 2,
      estimatedPintPrice: 6.5,
      openingHours: weekdayStandard,
      website: "https://www.thequeensheadlondon.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Queen's+Head+Acton+Street+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: true,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "Sunday",
      sportsInfo: "Music and beer-led rather than screens.",
      sundayRoastInfo: "Not currently tagged for roast.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["independent beer list", "live piano", "King's Cross convenience"],
        concerns: ["small footprint"]
      },
      busyProfile: { base: "moderate", centrality: 8, quizDay: 0, sportsPull: 0, roastPull: 0 },
      adminNotes: "Convenient small-group choice near King's Cross."
    },
    {
      id: "pub_014",
      googlePlaceId: "seed_lady_mildmay",
      name: "The Lady Mildmay",
      area: "Newington Green",
      address: "92 Mildmay Park, London N1 4PR",
      lat: 51.5507,
      lng: -0.0842,
      transitScore: 6,
      googleRating: 4.5,
      reviewCount: 740,
      priceLevel: 2,
      estimatedPintPrice: 6.3,
      openingHours: foodLed,
      website: "https://www.theladymildmay.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Lady+Mildmay+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "Monday",
      sportsInfo: "Neighbourhood pub with low sport focus.",
      sundayRoastInfo: "Sunday roast and seasonal pub food.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["neighbourhood", "roasts", "cosy rooms"],
        concerns: ["not the fastest Tube access"]
      },
      busyProfile: { base: "moderate", centrality: 4, quizDay: 1, sportsPull: 0, roastPull: 2 },
      adminNotes: "Good local-feeling option near the north/east midpoint."
    },
    {
      id: "pub_015",
      googlePlaceId: "seed_drapers_arms",
      name: "The Drapers Arms",
      area: "Islington",
      address: "44 Barnsbury Street, London N1 1ER",
      lat: 51.5391,
      lng: -0.1086,
      transitScore: 8,
      googleRating: 4.5,
      reviewCount: 1120,
      priceLevel: 3,
      estimatedPintPrice: 7.0,
      openingHours: foodLed,
      website: "https://www.thedrapersarms.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Drapers+Arms+Islington+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: true,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Food-led, no sports focus.",
      sundayRoastInfo: "Destination Sunday lunch.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["roast", "garden", "seasonal food"],
        concerns: ["higher spend", "booking advised"]
      },
      busyProfile: { base: "busy", centrality: 7, quizDay: null, sportsPull: 0, roastPull: 3 },
      adminNotes: "Use for roast searches when budget is less sensitive."
    },
    {
      id: "pub_016",
      googlePlaceId: "seed_prince_albert_battersea",
      name: "The Prince Albert",
      area: "Battersea",
      address: "85 Albert Bridge Road, London SW11 4PF",
      lat: 51.4783,
      lng: -0.1662,
      transitScore: 6,
      googleRating: 4.3,
      reviewCount: 1440,
      priceLevel: 2,
      estimatedPintPrice: 6.8,
      openingHours: centralLate,
      website: "https://www.princealbertbattersea.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Prince+Albert+Battersea+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Wednesday",
      sportsInfo: "Shows big fixtures.",
      sundayRoastInfo: "Sunday roast with garden demand.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["Battersea Park", "garden", "sport"],
        concerns: ["not ideal for north-east groups"]
      },
      busyProfile: { base: "moderate", centrality: 5, quizDay: 3, sportsPull: 2, roastPull: 2 },
      adminNotes: "Strong south-west choice with many tags."
    },
    {
      id: "pub_017",
      googlePlaceId: "seed_old_red_cow",
      name: "The Old Red Cow",
      area: "Barbican",
      address: "71 Long Lane, London EC1A 9EJ",
      lat: 51.5196,
      lng: -0.0974,
      transitScore: 9,
      googleRating: 4.4,
      reviewCount: 1190,
      priceLevel: 2,
      estimatedPintPrice: 6.7,
      openingHours: weekdayStandard,
      website: "https://www.theoldredcow.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Old+Red+Cow+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "",
      sportsInfo: "Shows sport in the bar.",
      sundayRoastInfo: "Sunday food available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["craft beer", "City location", "burger and roast"],
        concerns: ["City peak crowd"]
      },
      busyProfile: { base: "busy", centrality: 9, quizDay: null, sportsPull: 2, roastPull: 1 },
      adminNotes: "Central and convenient; better for transport than atmosphere."
    },
    {
      id: "pub_018",
      googlePlaceId: "seed_black_lion_kilburn",
      name: "The Black Lion",
      area: "Kilburn",
      address: "274 Kilburn High Road, London NW6 2BY",
      lat: 51.5426,
      lng: -0.1977,
      transitScore: 7,
      googleRating: 4.3,
      reviewCount: 1430,
      priceLevel: 2,
      estimatedPintPrice: 6.3,
      openingHours: centralLate,
      website: "https://www.blacklionkilburn.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Black+Lion+Kilburn+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: true,
        showing_football: true
      }),
      quizNight: "Thursday",
      sportsInfo: "Shows major sport.",
      sundayRoastInfo: "Sunday roast available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["large rooms", "garden", "events"],
        concerns: ["west-north bias"]
      },
      busyProfile: { base: "moderate", centrality: 4, quizDay: 4, sportsPull: 2, roastPull: 2 },
      adminNotes: "Feature-rich option for north-west groups."
    },
    {
      id: "pub_019",
      googlePlaceId: "seed_cat_mutton",
      name: "The Cat and Mutton",
      area: "Broadway Market",
      address: "76 Broadway Market, London E8 4QJ",
      lat: 51.5368,
      lng: -0.0617,
      transitScore: 7,
      googleRating: 4.2,
      reviewCount: 1600,
      priceLevel: 2,
      estimatedPintPrice: 6.6,
      openingHours: centralLate,
      website: "https://www.catandmutton.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Cat+and+Mutton+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: false,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "",
      sportsInfo: "Screens selected fixtures.",
      sundayRoastInfo: "Sunday food available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["Broadway Market", "lively evenings", "food"],
        concerns: ["weekends are crowded"]
      },
      busyProfile: { base: "busy", centrality: 6, quizDay: null, sportsPull: 1, roastPull: 1 },
      adminNotes: "Good Hackney-adjacent pub for lively nights."
    },
    {
      id: "pub_020",
      googlePlaceId: "seed_mayflower_rotherhithe",
      name: "The Mayflower",
      area: "Rotherhithe",
      address: "117 Rotherhithe Street, London SE16 4NF",
      lat: 51.501,
      lng: -0.0537,
      transitScore: 6,
      googleRating: 4.5,
      reviewCount: 3790,
      priceLevel: 3,
      estimatedPintPrice: 7.1,
      openingHours: foodLed,
      website: "https://www.mayflowerpub.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Mayflower+Rotherhithe+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: true,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Historic riverside pub, not sport-led.",
      sundayRoastInfo: "Sunday roast with river views.",
      reviewSummary: {
        sentiment: "Mostly positive",
        themes: ["river terrace", "historic setting", "food"],
        concerns: ["tourist demand", "higher spend"]
      },
      busyProfile: { base: "busy", centrality: 6, quizDay: null, sportsPull: 0, roastPull: 2 },
      adminNotes: "Memorable setting; not always the fairest transit choice."
    },
    {
      id: "pub_021",
      googlePlaceId: "seed_selkirk_tooting",
      name: "The Selkirk",
      area: "Tooting",
      address: "60 Selkirk Road, London SW17 0ES",
      lat: 51.4287,
      lng: -0.1654,
      transitScore: 7,
      googleRating: 4.4,
      reviewCount: 940,
      priceLevel: 2,
      estimatedPintPrice: 6.1,
      openingHours: foodLed,
      website: "https://www.theselkirk.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Selkirk+Tooting+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Tuesday",
      sportsInfo: "Shows football and rugby.",
      sundayRoastInfo: "Sunday roasts available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["Tooting local", "garden", "food"],
        concerns: ["south-west bias"]
      },
      busyProfile: { base: "moderate", centrality: 3, quizDay: 2, sportsPull: 2, roastPull: 2 },
      adminNotes: "Good south-west feature match."
    },
    {
      id: "pub_022",
      googlePlaceId: "seed_dog_bell_deptford",
      name: "The Dog and Bell",
      area: "Deptford",
      address: "116 Prince Street, London SE8 3JD",
      lat: 51.4818,
      lng: -0.0264,
      transitScore: 7,
      googleRating: 4.5,
      reviewCount: 1210,
      priceLevel: 2,
      estimatedPintPrice: 5.9,
      openingHours: weekdayStandard,
      website: "https://dogandbellse8.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Dog+and+Bell+Deptford+London",
      features: makeFeatures({
        sunday_roast: false,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: true,
        craft_beer: true,
        dart_board: true,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Thursday",
      sportsInfo: "Shows sport in a local-pub setting.",
      sundayRoastInfo: "Not tagged for Sunday roast.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["community pub", "beer garden", "value"],
        concerns: ["less central for north London"]
      },
      busyProfile: { base: "moderate", centrality: 3, quizDay: 4, sportsPull: 2, roastPull: 0 },
      adminNotes: "Excellent value and features for south-east groups."
    },
    {
      id: "pub_023",
      googlePlaceId: "seed_railway_tulse_hill",
      name: "The Railway Tavern",
      area: "Tulse Hill",
      address: "7 Station Rise, London SE27 9BW",
      lat: 51.4399,
      lng: -0.1052,
      transitScore: 6,
      googleRating: 4.2,
      reviewCount: 820,
      priceLevel: 2,
      estimatedPintPrice: 6.0,
      openingHours: weekdayStandard,
      website: "https://www.railwaytulsehill.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Railway+Tulse+Hill+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: true,
        craft_beer: false,
        dart_board: false,
        pool_table: true,
        showing_football: true
      }),
      quizNight: "Wednesday",
      sportsInfo: "Screens football and rugby.",
      sundayRoastInfo: "Sunday roasts available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["south London local", "quiz", "sport"],
        concerns: ["train-dependent for some groups"]
      },
      busyProfile: { base: "moderate", centrality: 3, quizDay: 3, sportsPull: 2, roastPull: 2 },
      adminNotes: "Broad feature coverage south of the river."
    },
    {
      id: "pub_024",
      googlePlaceId: "seed_white_horse_parsons",
      name: "The White Horse",
      area: "Parsons Green",
      address: "1-3 Parsons Green, London SW6 4UL",
      lat: 51.4732,
      lng: -0.2012,
      transitScore: 7,
      googleRating: 4.3,
      reviewCount: 2480,
      priceLevel: 3,
      estimatedPintPrice: 7.3,
      openingHours: centralLate,
      website: "https://www.whitehorsesw6.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+White+Horse+Parsons+Green+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "",
      sportsInfo: "Screens sport and big matches.",
      sundayRoastInfo: "Sunday roasts and classic pub food.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["beer selection", "Parsons Green", "sport"],
        concerns: ["premium prices"]
      },
      busyProfile: { base: "busy", centrality: 5, quizDay: null, sportsPull: 3, roastPull: 2 },
      adminNotes: "West/south-west classic with strong beer list."
    },
    {
      id: "pub_025",
      googlePlaceId: "seed_bedford_balham",
      name: "The Bedford",
      area: "Balham",
      address: "77 Bedford Hill, London SW12 9HD",
      lat: 51.4435,
      lng: -0.1507,
      transitScore: 8,
      googleRating: 4.2,
      reviewCount: 2420,
      priceLevel: 2,
      estimatedPintPrice: 6.5,
      openingHours: centralLate,
      website: "https://www.thebedford.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Bedford+Balham+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: true,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Tuesday",
      sportsInfo: "Shows sport and hosts events.",
      sundayRoastInfo: "Sunday roast available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["live comedy and music", "big rooms", "Balham station"],
        concerns: ["event nights can be loud"]
      },
      busyProfile: { base: "busy", centrality: 5, quizDay: 2, sportsPull: 2, roastPull: 2 },
      adminNotes: "Good event-led choice for south London groups."
    },
    {
      id: "pub_026",
      googlePlaceId: "seed_sun_camberwell",
      name: "The Sun of Camberwell",
      area: "Camberwell",
      address: "61-63 Coldharbour Lane, London SE5 9NS",
      lat: 51.4723,
      lng: -0.0927,
      transitScore: 5,
      googleRating: 4.2,
      reviewCount: 1260,
      priceLevel: 2,
      estimatedPintPrice: 6.2,
      openingHours: weekdayStandard,
      website: "https://www.thesunofcamberwell.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Sun+of+Camberwell+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: true,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "Monday",
      sportsInfo: "Not primarily a sports pub.",
      sundayRoastInfo: "Sunday roasts and pub food.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["garden", "food", "local crowd"],
        concerns: ["bus journeys for Tube-first groups"]
      },
      busyProfile: { base: "moderate", centrality: 4, quizDay: 1, sportsPull: 0, roastPull: 2 },
      adminNotes: "Good south-east social pick with garden."
    },
    {
      id: "pub_027",
      googlePlaceId: "seed_prince_wales_putney",
      name: "The Prince of Wales",
      area: "Putney",
      address: "138 Upper Richmond Road, London SW15 2SP",
      lat: 51.4609,
      lng: -0.213,
      transitScore: 7,
      googleRating: 4.2,
      reviewCount: 980,
      priceLevel: 2,
      estimatedPintPrice: 6.4,
      openingHours: weekdayStandard,
      website: "https://www.princeofwalesputney.com/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Prince+of+Wales+Putney+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: true,
        pub_quiz: true,
        live_music: false,
        craft_beer: false,
        dart_board: true,
        pool_table: true,
        showing_football: true
      }),
      quizNight: "Tuesday",
      sportsInfo: "Shows football and rugby.",
      sundayRoastInfo: "Sunday roast available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["sport", "games", "garden"],
        concerns: ["less convenient for east London"]
      },
      busyProfile: { base: "moderate", centrality: 3, quizDay: 2, sportsPull: 3, roastPull: 2 },
      adminNotes: "Game-friendly west/south-west pub."
    },
    {
      id: "pub_028",
      googlePlaceId: "seed_spread_eagle_camden",
      name: "The Spread Eagle",
      area: "Camden",
      address: "141 Albert Street, London NW1 7NB",
      lat: 51.5372,
      lng: -0.1432,
      transitScore: 9,
      googleRating: 4.3,
      reviewCount: 930,
      priceLevel: 2,
      estimatedPintPrice: 6.5,
      openingHours: weekdayStandard,
      website: "https://www.spreadeaglecamden.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Spread+Eagle+Camden+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: true,
        beer_garden: false,
        pub_quiz: true,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "Monday",
      sportsInfo: "Screens selected fixtures.",
      sundayRoastInfo: "Sunday roast available.",
      reviewSummary: {
        sentiment: "Positive",
        themes: ["Camden convenience", "food", "relaxed rooms"],
        concerns: ["can fill after Camden events"]
      },
      busyProfile: { base: "moderate", centrality: 7, quizDay: 1, sportsPull: 1, roastPull: 2 },
      adminNotes: "Reliable Camden midpoint option."
    },
    {
      id: "pub_029",
      googlePlaceId: "seed_george_strand",
      name: "The George",
      area: "Strand",
      address: "213 Strand, London WC2R 1AP",
      lat: 51.5135,
      lng: -0.1116,
      transitScore: 10,
      googleRating: 4.1,
      reviewCount: 2260,
      priceLevel: 2,
      estimatedPintPrice: 6.8,
      openingHours: centralLate,
      website: "https://www.greeneking.co.uk/pubs/greater-london/george",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+George+Strand+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: false,
        dart_board: false,
        pool_table: false,
        showing_football: true
      }),
      quizNight: "",
      sportsInfo: "Screens sport in central London.",
      sundayRoastInfo: "Sunday roast available.",
      reviewSummary: {
        sentiment: "Mixed positive",
        themes: ["central location", "historic pub", "easy meeting point"],
        concerns: ["tourist traffic", "less distinctive beer list"]
      },
      busyProfile: { base: "busy", centrality: 10, quizDay: null, sportsPull: 2, roastPull: 1 },
      adminNotes: "Central fallback, strong convenience but weaker product fit."
    },
    {
      id: "pub_030",
      googlePlaceId: "seed_royal_oak_borough",
      name: "The Royal Oak",
      area: "Borough",
      address: "44 Tabard Street, London SE1 4JU",
      lat: 51.5011,
      lng: -0.0915,
      transitScore: 9,
      googleRating: 4.5,
      reviewCount: 1460,
      priceLevel: 2,
      estimatedPintPrice: 6.4,
      openingHours: weekdayStandard,
      website: "https://royaloaklondon.co.uk/",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Royal+Oak+Borough+London",
      features: makeFeatures({
        sunday_roast: true,
        dog_friendly: false,
        beer_garden: false,
        pub_quiz: false,
        live_music: false,
        craft_beer: true,
        dart_board: false,
        pool_table: false,
        showing_football: false
      }),
      quizNight: "",
      sportsInfo: "Beer and food-led, not sport-led.",
      sundayRoastInfo: "Traditional Sunday lunch.",
      reviewSummary: {
        sentiment: "Very positive",
        themes: ["Harveys beer", "Borough location", "traditional feel"],
        concerns: ["small and popular"]
      },
      busyProfile: { base: "moderate", centrality: 8, quizDay: null, sportsPull: 0, roastPull: 2 },
      adminNotes: "Great beer and central-south location."
    }
  ];

  window.LPF_DATA = {
    FEATURE_DEFINITIONS: features,
    LOCATION_PRESETS: locationPresets,
    PUBS: pubs
  };
})();
